# Generated by Django 3.1.7 on 2021-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0003_auto_20210319_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags_category',
            field=models.CharField(choices=[('1', 'FOOD'), ('2', 'TRAVEL'), ('3', 'FASHION'), ('4', 'TECHNOLOGY'), ('5', 'BOOKS'), ('6', 'MUSIC'), ('7', 'FURNITURE'), ('8', 'STATIONARY & ART'), ('9', 'SKINCARE & BEAUTY')], default=1, max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_type',
            field=models.CharField(choices=[('1', 'FLASH SALE/DISCOUNT'), ('2', 'BUY MORE, SAVE MORE'), ('3', 'LOTTERY/COMPETITION'), ('4', 'GIFT BUNDLE/GIVEAWAY'), ('5', 'BUY 1 GET 1 FREE'), ('6', 'LOYALTY PROGRAM'), ('7', 'VOUCHER/COUPON'), ('8', 'FREE SHIPPING/RETURN'), ('9', 'OTHER')], default=1, max_length=32),
        ),
    ]
