# Generated by Django 3.1.7 on 2021-03-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0005_auto_20210322_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='visits',
        ),
    ]
