# Generated by Django 3.1.7 on 2021-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0006_auto_20210322_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
