# Generated by Django 3.1.7 on 2021-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0007_post_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
