# Generated by Django 3.1.7 on 2021-03-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0009_auto_20210326_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucherMe.userprofile'),
        ),
    ]
