# Generated by Django 3.1.7 on 2021-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0011_auto_20210326_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags_category',
            field=models.CharField(max_length=32),
        ),
    ]
