# Generated by Django 3.1.7 on 2021-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0012_auto_20210326_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='business_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags_category',
            field=models.CharField(choices=[('1', 'FOOD'), ('2', 'TRAVEL'), ('3', 'FASHION'), ('4', 'TECHNOLOGY'), ('5', 'BOOKS'), ('6', 'MUSIC'), ('7', 'FURNITURE'), ('8', 'STATIONARY & ART'), ('9', 'SKINCARE & BEAUTY')], default=1, max_length=32),
        ),
    ]
