# Generated by Django 3.1.7 on 2021-03-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0016_auto_20210329_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='business_id',
            new_name='business',
        ),
    ]
