# Generated by Django 3.1.7 on 2021-03-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0017_auto_20210329_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visits',
        ),
    ]
