# Generated by Django 3.1.7 on 2021-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0018_remove_post_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
