# Generated by Django 3.1.7 on 2021-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0020_auto_20210329_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
