# Generated by Django 3.1.7 on 2021-03-31 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucherMe', '0021_auto_20210329_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='likes',
        ),
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='business_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
