# Generated by Django 3.1.7 on 2021-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherMe', '0022_auto_20210331_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='likes',
        ),
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
